[build]
  command = "npm run generate"
  publish = ".output/public"
  node_version = "22.19.0"

[build.environment]
  NPM_FLAGS = "--no-audit --no-fund"
  NODE_VERSION = "22.19.0"
  CI = "true"

[[plugins]]
  package = "@netlify/plugin-cache"
  [plugins.inputs]
    paths = ["node_modules/.pnpm", "node_modules", ".output", ".nuxt"]

[functions]
  node_bundler = "esbuild"

# No redirects needed for a fully generated site


